ncaa_d1_baseball_stats:
  target: dev
  outputs:
    dev:
      dataset: ncaa_d1_baseball_stats_stg
      fixed_retries: 1
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
      location: "{{ env_var('GCP_LOCATION') }}"
      method: service-account
      priority: interactive
      project: ~/ncaa_d1_baseball_stats/credentials/gcp-credentials.json
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: ncaa_d1_baseball_stats_stg
      fixed_retries: 1
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
      location: "{{ env_var('GCP_LOCATION') }}"
      method: service-account
      priority: interactive
      project: ~/ncaa_d1_baseball_stats/credentials/gcp-credentials.json
      threads: 4
      timeout_seconds: 300
      type: bigquery