version: 2

sources:
  - name: stg
    database: "{{ env_var('DBT_ENV_GCP_PROJECT_ID')}}"
    schema: "{{ env_var('DBT_ENV_BIG_QUERY_TABLE_STG')}}"
    tables:
      - name: "{{ env_var('DBT_ENV_BIG_QUERY_TABLE_STG')}}"

models:
    - name: stg_all_batting_box_scores
      description: >
        All batting box scores scraped on a daily basis for all Division 1 Baseball Games in the 2024 Season.
        Each row contains a hitter's stats for a given game.
      