ncaa_d1_baseball_stats:
  outputs:
    dev:
      # dataset: "{{ env_var('BIG_QUERY_TABLE_NAME_STG') }}" 
      schema: dev_ncaa_d1_baseball_stats
      fixed_retries: 1
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
      location: "{{ env_var('GCP_REGION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      # dataset: "{{ env_var('BIG_QUERY_TABLE_NAME_STG') }}" 
      schema: prod_d1_baseball_stats_prod
      fixed_retries: 1
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
      location: "{{ env_var('GCP_REGION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev