ncaa_d1_baseball_stats:
  outputs:
    dev:
      fixed_retries: 1
      keyfile: credentials/gcp-credentials.json
      location: us-west1
      method: service-account
      priority: interactive
      project: ncaa-d1-baseball-stats-project
      schema: dev_ncaa_d1_baseball_stats
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      fixed_retries: 1
      keyfile: credentials/gcp-credentials.json
      location: us-west1
      method: service-account
      priority: interactive
      project: ncaa-d1-baseball-stats-project
      schema: prod_ncaa_d1_baseball_stats
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
